import type { SceneManagerDomRefs } from './types.js';

export function getSceneManagerDomRefs(): SceneManagerDomRefs {
    return {
        hierarchyTabBtn: document.getElementById('scene-tab-hierarchy') as HTMLButtonElement | null,
        inspectorTabBtn: document.getElementById('scene-tab-inspector') as HTMLButtonElement | null,
        hierarchyPanelEl: document.getElementById('scene-panel-hierarchy'),
        inspectorPanelEl: document.getElementById('scene-panel-inspector'),
        listEl: document.getElementById('scene-object-list'),
        listCountEl: document.getElementById('scene-object-count'),
        detailsEl: document.getElementById('scene-object-details'),
        transformXEl: document.getElementById('scene-transform-x') as HTMLInputElement | null,
        transformYEl: document.getElementById('scene-transform-y') as HTMLInputElement | null,
        transformZEl: document.getElementById('scene-transform-z') as HTMLInputElement | null,
        rotateControlsEl: document.getElementById('scene-rotate-controls') as HTMLDivElement | null,
        rotateResetBtn: document.getElementById('scene-rotate-reset-btn') as HTMLButtonElement | null,
        addTypeOpenBtn: document.getElementById('scene-add-type-open-btn') as HTMLButtonElement | null,
        addTypeSelectionCardEl: document.getElementById('scene-add-type-selection-card') as HTMLDivElement | null,
        addTypeCurrentIconEl: document.getElementById('scene-add-type-current-icon'),
        addTypeCurrentEl: document.getElementById('scene-add-type-current'),
        addTypeCurrentTextEl: document.getElementById('scene-add-type-current-text'),
        addTypeEl: document.getElementById('scene-add-type') as HTMLSelectElement | null,
        addTypeModalEl: document.getElementById('scene-type-modal') as HTMLDivElement | null,
        addTypeModalPreviewEl: document.getElementById('scene-type-modal-preview') as HTMLDivElement | null,
        addTypeModalPreviewViewportEl: document.getElementById('scene-type-modal-preview-viewport') as HTMLDivElement | null,
        addTypeModalPreviewTitleEl: document.getElementById('scene-type-modal-preview-title') as HTMLDivElement | null,
        addTypeModalPreviewTextEl: document.getElementById('scene-type-modal-preview-text') as HTMLDivElement | null,
        addTypeModalGridEl: document.getElementById('scene-type-modal-grid') as HTMLDivElement | null,
        addTypeModalApplyBtn: document.getElementById('scene-type-modal-apply-btn') as HTMLButtonElement | null,
        addTypeModalSelectionCardEl: document.getElementById('scene-type-modal-selection-card') as HTMLDivElement | null,
        addTypeModalSelectionIconEl: document.getElementById('scene-type-modal-selection-icon'),
        addTypeModalSelectionTitleEl: document.getElementById('scene-type-modal-selection-title'),
        addTypeModalSelectionTextEl: document.getElementById('scene-type-modal-selection-text'),
        addTypeModalPrevBtn: document.getElementById('scene-type-modal-prev-btn') as HTMLButtonElement | null,
        addTypeModalNextBtn: document.getElementById('scene-type-modal-next-btn') as HTMLButtonElement | null,
        addTypeModalCloseBtn: document.getElementById('scene-type-modal-close-btn') as HTMLButtonElement | null,
        addTypeModalPageIndicatorEl: document.getElementById('scene-type-modal-page-indicator') as HTMLDivElement | null,
        addDictionaryWrapEl: document.getElementById('scene-add-dictionary-wrap') as HTMLLabelElement | null,
        addDictionaryEl: document.getElementById('scene-add-dictionary') as HTMLSelectElement | null,
        addValueWrapEl: document.getElementById('scene-add-value-wrap') as HTMLLabelElement | null,
        addValueEl: document.getElementById('scene-add-value') as HTMLInputElement | null,
        addFloorsWrapEl: document.getElementById('scene-add-floors-wrap') as HTMLLabelElement | null,
        addFloorsEl: document.getElementById('scene-add-floors') as HTMLInputElement | null,
        addBuildingSettingsEl: document.getElementById('scene-add-building-settings') as HTMLDivElement | null,
        addBuildingFloorEl: document.getElementById('scene-add-building-floor') as HTMLInputElement | null,
        addBuildingFaceEl: document.getElementById('scene-add-building-face') as HTMLSelectElement | null,
        addBuildingWindowEl: document.getElementById('scene-add-building-window') as HTMLSelectElement | null,
        addBuildingKindEl: document.getElementById('scene-add-building-kind') as HTMLSelectElement | null,
        addBuildingIncidentsEl: document.getElementById('scene-add-building-incidents') as HTMLTextAreaElement | null,
        addBuildingAppendBtn: document.getElementById('scene-add-building-append-btn'),
        addBuildingClearBtn: document.getElementById('scene-add-building-clear-btn'),
        addMapSettingsEl: document.getElementById('scene-add-map-settings') as HTMLDivElement | null,
        addMapSummaryEl: document.getElementById('scene-add-map-summary') as HTMLDivElement | null,
        addMapRowsEl: document.getElementById('scene-add-map-rows') as HTMLInputElement | null,
        addMapColumnsEl: document.getElementById('scene-add-map-columns') as HTMLInputElement | null,
        addMapStartIdEl: document.getElementById('scene-add-map-start-id') as HTMLInputElement | null,
        addMapIdStepEl: document.getElementById('scene-add-map-id-step') as HTMLInputElement | null,
        addMapMarkerSizeEl: document.getElementById('scene-add-map-marker-size') as HTMLInputElement | null,
        addMapRotationEl: document.getElementById('scene-add-map-rotation') as HTMLInputElement | null,
        addMapGapXEl: document.getElementById('scene-add-map-gap-x') as HTMLInputElement | null,
        addMapGapYEl: document.getElementById('scene-add-map-gap-y') as HTMLInputElement | null,
        addMapTraversalEl: document.getElementById('scene-add-map-traversal') as HTMLSelectElement | null,
        addMapStartCornerEl: document.getElementById('scene-add-map-start-corner') as HTMLSelectElement | null,
        addMapAnchorEl: document.getElementById('scene-add-map-anchor') as HTMLSelectElement | null,
        addMapSnakeEl: document.getElementById('scene-add-map-snake') as HTMLInputElement | null,
        addPointsWrapEl: document.getElementById('scene-add-points-wrap') as HTMLLabelElement | null,
        addPointsEl: document.getElementById('scene-add-points') as HTMLTextAreaElement | null,
        addBtn: document.getElementById('scene-add-btn'),
        presetTypeEl: document.getElementById('scene-preset-type') as HTMLSelectElement | null,
        presetBtn: document.getElementById('scene-preset-btn'),
        selectedDictionaryWrapEl: document.getElementById('scene-selected-dictionary-wrap') as HTMLLabelElement | null,
        selectedDictionaryEl: document.getElementById('scene-selected-dictionary') as HTMLSelectElement | null,
        selectedValueWrapEl: document.getElementById('scene-selected-value-wrap') as HTMLLabelElement | null,
        selectedValueEl: document.getElementById('scene-selected-value') as HTMLInputElement | null,
        selectedFloorsWrapEl: document.getElementById('scene-selected-floors-wrap') as HTMLLabelElement | null,
        selectedFloorsEl: document.getElementById('scene-selected-floors') as HTMLInputElement | null,
        selectedBuildingSettingsEl: document.getElementById('scene-selected-building-settings') as HTMLDivElement | null,
        selectedBuildingFloorEl: document.getElementById('scene-selected-building-floor') as HTMLInputElement | null,
        selectedBuildingFaceEl: document.getElementById('scene-selected-building-face') as HTMLSelectElement | null,
        selectedBuildingWindowEl: document.getElementById('scene-selected-building-window') as HTMLSelectElement | null,
        selectedBuildingKindEl: document.getElementById('scene-selected-building-kind') as HTMLSelectElement | null,
        selectedBuildingIncidentsEl: document.getElementById('scene-selected-building-incidents') as HTMLTextAreaElement | null,
        selectedBuildingAppendBtn: document.getElementById('scene-selected-building-append-btn'),
        selectedBuildingClearBtn: document.getElementById('scene-selected-building-clear-btn'),
        selectedPointsWrapEl: document.getElementById('scene-selected-points-wrap') as HTMLLabelElement | null,
        selectedPointsEl: document.getElementById('scene-selected-points') as HTMLTextAreaElement | null,
        applyMetaBtn: document.getElementById('scene-apply-meta-btn'),
        appendPointBtn: document.getElementById('scene-append-point-btn'),
        visualEditBtn: document.getElementById('scene-visual-edit-btn'),
        deleteBtn: document.getElementById('scene-delete-btn'),
        groupBtn: document.getElementById('scene-group-btn'),
        ungroupBtn: document.getElementById('scene-ungroup-btn'),
        resetDroneBtn: document.getElementById('scene-drone-origin-btn'),
        clearSelectionBtn: document.getElementById('scene-clear-selection-btn'),
        modeTranslateBtn: document.getElementById('scene-mode-translate'),
        modeRotateBtn: document.getElementById('scene-mode-rotate'),
        modeScaleBtn: document.getElementById('scene-mode-scale')
    };
}
